<!DOCTYPE prd_dtl [
        <!ELEMENT prd_dtl (prd_info|selected_vndr|vndr_list)*>
        <!ELEMENT prd_info (title|mpno|cpno|mfr|cntrct_num|MAS|SIN|Warranty|MadeIn|wt|desc|photo_url)*>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT mpno (#PCDATA)>
        <!ELEMENT cpno (#PCDATA)>
        <!ELEMENT mfr (#PCDATA)>
        <!ELEMENT cntrct_num (#PCDATA)>
        <!ELEMENT MAS (#PCDATA)>
        <!ELEMENT SIN (#PCDATA)>
        <!ELEMENT Warranty (#PCDATA)>
        <!ELEMENT MadeIn (#PCDATA)>
        <!ELEMENT wt (#PCDATA)>
        <!ELEMENT desc (#PCDATA)>
        <!ELEMENT photo_url (#PCDATA)>
        <!ELEMENT selected_vndr (price|vndr_name)*>
        <!ELEMENT price (#PCDATA)>
        <!ELEMENT vndr_name (#PCDATA)>
        <!ELEMENT vndr_list (vndr)*>
        <!ELEMENT vndr (price|vndr_name|socio_inds|delivery_dt|min|FOB|shipping)*>
        <!ELEMENT socio_inds (ind)*>
        <!ELEMENT ind (#PCDATA)>
        <!ELEMENT delivery_dt (#PCDATA)>
        <!ELEMENT min (#PCDATA)>
        <!ELEMENT FOB (#PCDATA)>
        <!ELEMENT shipping (#PCDATA)>
        ]>
<prd_dtl xmlns="prod_dtl">
    <prd_info>
        <title>CANON CLI-221 GRAY INK CARTRIDGE</title>
        <mpno>CLI221G</mpno>
        <cpno>OEM-CLI221G</cpno>
        <mfr>CANON</mfr>
        <cntrct_num>GS-02F-0073P (ends: Jan 22, 2014)</cntrct_num>
        <MAS>75/75 200</MAS>
        <SIN>75/75 200</SIN>
        <Warranty>STANDARD WARRANTY</Warranty>
        <MadeIn>UNITED STATES OF AMERICA</MadeIn>
        <wt>0.007 LB</wt>
        <desc>Pacific Ink. FREE DELIVERY. WOMAN OWNED SMALL BUSINESS. Quote call 858-952-1103. OEM # CLI-221Pacific Ink has a surplus buy back program. If you have excess CLI-221 cartridges, or any others, trade them in for cartridges you need. Contact us for more details.Works in Canon PIXMAiP3600, Canon PIXMAiP4600, Canon PIXMAMP620, Canon PIXMAMP980, Canon PIXMAMX860, Canon PIXMAPMFP1, Canon PIXMAPMFP3, Canon PIXMASFP1, Canon PIXMASFP2, Canon PIXUSMP610, Canon PIXUSMX860, Canon PIXMAMP640, Canon PIXMAMP560
</desc>
        <photo_url>https://www.gsaadvantage.gov/images/products/GS-02F-0073P/CLI221G.JPG</photo_url>
    </prd_info>
    <selected_vndr>
        <price>$13.57 EA</price>
        <vndr_name>Pacific Ink, Inc.</vndr_name>
    </selected_vndr>
    <vndr_list>
        <vndr>
            <price>$11.86 EA</price>
            <vndr_name>American Toner LLC</vndr_name>
            <socio_inds>
                <ind>s</ind>
                <ind>w</ind>
            </socio_inds>
            <delivery_dt>30 days delivered ARO</delivery_dt>
            <min></min>
            <FOB></FOB>
            <shipping></shipping>
        </vndr>
        <vndr>
            <price>$13.57 EA</price>
            <vndr_name>Pacific Ink</vndr_name>
            <socio_inds>
                <ind></ind>
                <ind></ind>
                <ind></ind>
            </socio_inds>
            <delivery_dt>Delivery Date</delivery_dt>
            <min></min>
            <FOB></FOB>
            <shipping></shipping>
        </vndr>
        <vndr>
            <price>Price</price>
            <vndr_name>Vendor Name</vndr_name>
            <socio_inds>
                <ind>s</ind>
                <ind>w</ind>
            </socio_inds>
            <delivery_dt>5 days delivered ARO</delivery_dt>
            <min></min>
            <FOB></FOB>
            <shipping></shipping>
        </vndr>
    </vndr_list>
</prd_dtl>